title: www.DanLevy.net
email: dan@danlevy.net

description: Devout Developer
disqus_shortname: danlevy
reading_time:     true
words_per_minute: 50 #was 200, 50 is better for code
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:
# baseurl: "/" # the subpath of your site, e.g. /blog/

# Owner/author information
owner:
  name:           Dan Levy
  avatar:         avatar.jpg
  bio:            "Devout Programmer"
  email:          Dan@DanLevy.net
  # Social networking links used in footer. Update and remove as you like.
  twitter:        justsml
  facebook:       justsml
  github:         justsml
  stackexchange:
  linkedin: realdanlevy
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus: +justsml

# Background image to be tiled on all pages
background: abstract-3.jpg
destination: ./public

# Analytics and webmaster tools stuff goes here
google_analytics: UA-59708923-1
google_verify: aQmDDAD2Nia138WekOPnb9tQ_J9AcRUDLbij5PxCmes
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 1A9E3CE623BA981E829FE1023285585D

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Denver
future:      true
# pygments:    true


markdown: rdiscount
highlighter: pygments

# markdown:    kramdown
# highlighter: redcarpet

# highlighter: pygments
# markdown:    rdiscount

gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

redcarpet:
  extensions:
    - tables
    - autolink
    - no_intra_emphasis
    - lax_spacing
    -

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
    - generate_toc
# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title/
permalink: /:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM
  use_coderay: false

  coderay:
    coderay_line_numbers: true
    coderay_line_numbers_start: 1
    coderay_tab_width: 2
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess", "cv", "assets", "images", "css"]

exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
